# Copy these values to your ESPHome secrets.yaml and replace them.

wifi_ssid: "YOUR_WIFI_SSID"
wifi_password: "YOUR_WIFI_PASSWORD"
rfid_api_key: "PASTE_YOUR_32_BYTE_BASE64_ESPHOME_API_KEY_HERE"
rfid_ota_password: "CHANGE_ME"
rfid_fallback_password: "CHANGE_ME_TOO"
